<?php include 'head.php'; ?>
<?php include 'menu.php'; ?>
<h1>
Matt Ridley: The beginning of the end of wind
</h1>
<h2>Sunday, March 4th 2012</h2>
<p><a href="">Here</a> is my Spectator cover story on wind power:</p>
<p>To the nearest whole number, the percentage of the world's energy that comes from wind turbines today is: zero. Despite the regressive subsidy (pushing pensioners into fuel poverty while improving the wine cellars of grand estates), despite tearing rural communities apart, killing jobs, despoiling views, erecting pylons, felling forests, killing bats and eagles, causing industrial accidents, clogging motorways, polluting lakes in Inner Mongolia with the toxic and radioactive tailings from refining neodymium, a ton of which is in the average turbine - despite all this, the total energy generated each day by wind has yet to reach half a per cent worldwide.</p>
<p>If wind power was going to work, it would have done so by now. The people of Britain see this quite clearly, though politicians are often wilfully deaf. The good news though is that if you look closely, you can see David Cameron's government coming to its senses about the whole fiasco. The biggest investors in offshore wind - Mitsubishi, Gamesa and Siemens - are starting to worry that the government's heart is not in wind energy any more. Vestas, which has plans for a factory in Kent, wants reassurance from the Prime Minister that there is the political will to put up turbines before it builds its factory.</p>
<p>This forces a decision from Cameron - will he reassure the turbine magnates that he plans to keep subsidising wind energy, or will he retreat? The political wind has certainly changed direction. George Osborne is dead set against wind farms, because it has become all too clear to him how much they cost. The Chancellor's team quietly encouraged MPs to sign a letter to No. 10 a few weeks ago saying that ‘in these financially straitened times, we think it is unwise to make consumers pay, through taxpayer subsidy, for inefficient and intermittent energy production that typifies onshore wind turbines'.</p>
<p>Putting the things offshore may avoid objections from the neighbours, but (Chancellor, beware!) it makes even less sense, because it costs you and me - the taxpayers - double. I have it on good authority from a marine engineer that keeping wind turbines upright in the gravel, tides and storms of the North Sea for 25 years is a near hopeless quest, so the repair bill is going to be horrific and the output disappointing. Already the grouting in the foundations of hundreds of turbines off Kent, Denmark and the Dogger Bank has failed, necessitating costly repairs.</p>
<p>In Britain the percentage of total energy that comes from wind is only 0.6 per cent. According to the Renewable Energy Foundation, ‘policies intended to meet the EU Renewables Directive in 2020 will impose extra consumer costs of approximately £15 billion per annum’ or £670 per household. It is difficult to see what value will be got for this money. The total carbon emissions saved by the great wind rush is probably below 1 per cent, because of the need to keep fossil fuels burning as back-up when the wind does not blow. It may even be a negative number. </p>
<p>America is having far better luck. Carbon emissions in the United States fell by 7 per cent in 2009, according to a Harvard study. But the study concluded that this owes less to the recession that year than the falling price of natural gas - caused by the shale gas revolution. (Burning gas emits less than half as much carbon dioxide as coal for the same energy output.) The gas price has fallen even further since, making coal seem increasingly pricey by comparison. All over America, from Utah to West Virginia, coal mines are being closed and coal plants idled or cancelled. (The US Energy Information Administration calculates that every $4 spent on shale purchases the same energy as $25 spent on oil: at this rate, more and more vehicles will switch to gas.)</p>
<p>So even if you accept the most alarming predictions of climate change, those turbines that have ruined your favourite view are doing nothing to help. The shale gas revolution has not only shamed the wind industry by showing how to decarbonise for real, but has blown away its last feeble argument - that diminishing supplies of fossil fuels will cause their prices to rise so high that wind eventually becomes competitive even without a subsidy. Even if oil stays dear, cheap gas is now likely to last many decades.</p>
<?php include 'foot.php'; ?>