<?php include 'head.php'; ?>
<?php include 'menu.php'; ?>
<h1>Which kills more ideology or religion Andrew Kenny Spectator 28May05</h1>
<h2>SATURDAY, 28TH MAY 2005</h2>
<p>Andrew Kenny says the real killer in Africa is the ban on DDT, not the ban on condoms
The sun set on the 20th century more than four years ago but you can still see a blood-red glow on the horizon. The century that saw unprecedented technological progress also saw unprecedented slaughter. Previously, religion had served mankind's deep needs for explanation, order, spiritual comfort and transcendental meaning. Now a new and hideous thing was summoned up to serve the same needs. The thing was ideology, and in a few decades it caused more bloodshed than millennia of religion. It was darker and more irrational, and contained within it something unknown to all the Religions of the Book: a death wish. Religious leaders, however bad they may be, however prone to hubris and hatred, are constrained by fear of God above and by ancient tradition and wisdom. Ideological leaders have no such constraints. </p>
<p>Recently there have been hysterical attacks on the new Pope Benedict, including the charge that he has the blood of millions of Africans on his hands because of the Church's ban on condoms in a continent ravaged by Aids. I live in Africa, I am an atheist and I think the Church's prohibition of contraception is wrong, but I want to defend the Pope. To do so, I must compare the good and bad of the Church in Africa with those of the ideologies. </p>
<p>Ideology comes in three colours: red, brown and green, representing Marxism, fascism and environmental extremism. Judged on sheer evil, the worst crime in history was brown, the Nazi genocide, although the reds slaughtered more people. The death toll (difficult to measure) is roughly, Hitler's holocaust 6 million, Stalin's famine and terror 8 million, and Mao's famine 30 million. But the greens have topped them all. In a single crime they have killed about 50 million people. In purely numerical terms, it was the worst crime of the 20th century. It took place in the USA in 1972. It was the banning of DDT. </p>
<p>Malaria is one of the most terrible diseases mankind has ever faced. In the 16th and 17th centuries it decimated Europe (it is mentioned in Shakespeare's plays as 'ague' and probably killed Cromwell). It brought death over the world on a gigantic scale. In 1939 Paul Muller, a Swiss chemist, discovered that a synthetic chemical, DDT (dichloro-diphenyl-trichloroethane), killed flies, mosquitoes and other invertebrates. It was used to stop a typhus epidemic in Italy in 1943. US troops in the second world war dusted themselves with it against lice. It proved spectacularly successful against malaria-bearing mosquitoes. In 1948 Muller won the Nobel Prize for his work on DDT. By 1967, thanks to DDT, malaria had been eradicated from all rich countries, and was being eradicated in Latin America, tropical Asia and three countries in Africa. In 1970 the US National Academy of Sciences stated: 'To only a few chemicals does man owe so great a debt as to DDT.... In little more than two decades, DDT has prevented 500 million human deaths, due to malaria, that otherwise would have been inevitable.'</p>
<p>In 1971 DDT was poised to rid the world of malaria. In 1972 it was banned. </p>
<p>The ban, decided in the USA by William Ruckelshaus, an administrator of the Environmental Protection Agency, was a travesty. Ruckelshaus ignored the massive evidence that DDT was not harmful to man or wildlife and refused to give reasons for the ban. It was purely ideological. This was the time of Rachel Carson's mendacious book Silent Spring, about the horrors of pesticides, when the newly emerging green ideology was looking for a cause célèbre. Study after study has shown that DDT, even when abused, as it certainly was, did not cause cancer or serious disease in humans, did not harm bald eagles or peregrine falcons, and did not cause eggshell thinning. None of this mattered. The greens, leaning heavily on Ruckelshaus, were determined to ban it and did so, with catastrophic consequences for poor people with dark skins. Tens of millions of humans were sacrificed on the green altar. </p>
<p>The US extended the ban overseas by various measures, including refusing aid to countries that used DDT. Other rich countries, urged on by their greens, followed suit. Malaria, which had been in retreat, came surging back, killing multitudes. It is estimated that more than 2 million people now die every year of malaria, most of them in Africa. In 1996, under green pressure, South Africa stopped using DDT. Malaria deaths immediately shot up. South Africa went back to DDT, and deaths fell away. The South African government, which talks nonsense about Aids, is sensible on malaria, allowing DDT to be sprayed on the inside of dwellings, its best use. To some extent the rich countries have relaxed their ban on DDT but prohibitions remain, including from the EU, and nothing is done by them to encourage this cheap, safe, highly effective method of eradicating malaria. </p>
<p>I have heard not one word of pity or regret from any green organisation about the vast loss of human life caused by the ban on DDT. On the contrary, they seem to regard it as a glorious triumph. The likely reason was spelled out with chilling clarity by Charles Wurster of the Environmental Defence Fund in the USA in 1971 when it was pointed out to him that DDT saved the lives of poor people in poor countries. He said: 'So what? People are the main cause of our problems. We have too many of them. We need to get rid of some of them and this is as good a way as anything.' </p>
<p>Here is the key difference between ideology and religion. Here is the fundamental reason why so many ideologues hate the Catholic Church. It was best articulated by Savitri Devi, sometimes called 'Hitler's Priestess', the green mystic, pagan and worshipper of Hitler, who said that Christianity was 'centred on man' whereas her green and fascist creed was 'centred on life'. She is right. The Bible tells men to 'be fruitful and multiply' and 'have dominion' over other living things. This is anathema to the greens. (Greens are closer to browns than they are to reds. The red ideal is progress via central committees, steel works and tons of concrete. The brown ideal is a static idyll of forests, Alsatian dogs and flaxen-haired maidens tripping through the wheatfields.) Of course when the Bible speaks of 'man', it means all of mankind, whereas when Devi speaks of 'life', she means only selected types of life, such as Aryans and tigers. Some other forms of life are best exterminated. </p>
<p>I have mentioned only one of the crimes of the ideologues, although the worst. In Africa they have also caused dreadful misery by promoting destructive policies such as command economies and by financing and encouraging calamitous leaders such as Julius Nyerere, who drove the economy of Tanzania to destitution. </p>
<p>The Pope in Africa follows the Biblical injunction. He is for human life. His guides are the enduring truths of his faith and the Word of God. These, and not the latest political fashion or trend in sociology departments, are what direct him. However, the Catholic prohibition on contraception does not seem to have any Biblical foundation, apart from the story of Onan spilling his seed on the ground, which is a special case. It seems more likely to have come from Aristotle, the source of much bad doctrine. It is illogical to allow contraception by the rhythm method while banning other methods. Why is it more natural to study a calendar before engaging in sexual congress than to put a bit of rubber over your winky? However, this is the teaching. What harm has it done? </p>
<p>Aids is devastating Africa, even if the exact scale of the devastation is not well known. Condoms are an effective barrier against the HIV virus (despite silly attempts to pretend otherwise). However, in South Africa it is believed that a high proportion of infection comes from 'non-consensual sex', where the man is never going to use a condom, even if the Pope orders him to do so. African women tell us that their husbands and lovers would beat them up if they asked them to use them. The breakdown of the black family and the high incidence of married middle-aged men copulating with young girls hugely exacerbate the spread of HIV infection. The Pope's message of abstinence outside married life and faithfulness within it would be effective if it were followed - more so than a message of free love and condoms. In Uganda President Museveni seems to be very successful in reducing HIV incidence by calling publicly for abstinence, faithfulness and condoms, which seems to me the best possible advice. (The ideologues are furious with anyone who promotes family life and seem actually frightened of the concept of abstinence.) What the balance of effects is between the Church's promotion of faithful family life and its ban on condoms is impossible to calculate, but my guess is that it has prevented more infections than it has caused. To say that the Pope is a mass murderer is ridiculous. </p>
<p>The Catholic Church has been an immeasurable force for good in Africa. It has educated, treated, fed and brought hope to a multitude of Africans. It has quietly worked against evil systems, such as apartheid and African tyranny, in just the same way that the great John Paul II worked against communism. While rich young things from international aid agencies flit briefly through Africa in designer safari jackets and air-conditioned 4x4s before settling down to cosy careers in the rich countries, humble priests and nuns spend heroic lives in little villages in the hills and bushes of Africa spreading a gospel of learning, medicine, nutrition and decency, and preaching the equal worth of all men and the promise of redemption for everybody. </p>
<p>As for the other charge against Pope Benedict, I found myself chatting to a most genial man in a Cape Town pub shortly after his election. I said to him that Ratzinger was in the Hitler Youth. He said cheerfully, 'So was I!' In 1942, at the age of 12, he was co-opted. He said it was like compulsory Boy Scouts. While Jews were being transported to the death camps elsewhere in the Reich, adolescent Germans in the Hitler Youth, like Ratzinger and my affable drinking companion, were picking up litter, making Christmas presents for poor children and helping old ladies across the street. Hardly the mark of Cain. </p>
<p>Pope John Paul II was the most consistent moral authority of the 20th century. Benedict seems likely to continue in his path. (Strangely enough, he looks to me rather like Richard Dawkins, the great evolutionist, atheist and Pope-basher, both having fine, handsome, intelligent faces.) I wish the Catholic Church would change its stance on contraception, but its prohibition is a small cost compared with the enormous benefit the Church brings to Africa. </p>
<p><em>The Spectator, 22 Old Queen Street, London, SW1H 9HP. All Articles and Content Copyright ©2007 by The Spectator (1828) Ltd. All Rights Reserved</em> 
</p>
<?php include 'foot.php'; ?>