<?php include 'head.php'; ?>
<?php include 'menu.php'; ?>
<h1>
FRIENDS OF THE EARTH
</h1>
<p>The Friends of the Earth (FoE) have drawn attention to the number of deaths from hypothermia ( 25000 in winter according to  the  Office of  National  Statistics)and have called for better insulation in the homes of elderly people (Journal, 12 May).</p>
<p>We can all support this, but the reality is that the major cause of high electricity bills is the fact that we are building offshore wind turbines at a cost of approximately 9p per  kwhr as opposed to 2.2p per kwhr for nuclear electricity.  Unfortunately, FoE are opposed to civil nuclear power stations.  It would be unkind to say that FoE are hypocritical but they are clearly ignorant. </p>
<p>It is 10 years since James Lovelock, who was made a Companion of Honour for his work that enabled us to solve the problem of the hole in the ozone layer, said that any intelligent person who was concerned about carbon dioxide emissions should press for the immediate construction of nuclear power stations.</p>
<p>Nuclear is, of course, by far the safest method of generating electricity.  In the years since Chernobyl, the figures are as follows:</p>
<table>
<tr><th>Fuel</th><th>No. of deaths</th><th>Deaths per terawatt year of electricity generated</th></tr>
<tr><td>Coal</td><td>6400</td><td>342</td></tr>
<tr><td>Natural Gas</td><td>1200</td><td>85</td></tr>
<tr><td>Hydro Electricity</td><td>4000</td><td>883</td></tr>
<tr><td>Nuclear</td><td>33</td><td>8</td></tr>
</table>
<p>The final column shows the number of deaths suffered for every million megawatts of electricity supplied in a year (one terawatt year).  The amount of electricity generated by wind in this period was less than one terawatt year, so a death toll for wind power is not included but is expected to be very high as the construction industry has a high death rate outside the atheistic Soviet Union there had never been a death caused  by  failure of a nuclear reactor until  this  year.</p>
<p>The fact that nuclear power is safe was sadly confirmed recently in Japan.  The Japanese earthquake cost 24,000 lives, including  thousands  in the fire following the destruction of an oil refinery and also seven at the nuclear power station.  It is to be hoped that FoE will look at facts and not carry on with their irrational opposition to the safest and cheapest form of zero carbon electricity.</p>
<?php include 'foot.php'; ?>