<?php include 'head.php'; ?>
<?php include 'menu.php'; ?>
<h1>Kielder Wind Turbines</h1>
<p>Dear  Mr  Aitken</p> 
<p>The proposal to erect 100 wind- turbines at Kielder (Journal, Friday 9 August) is utter madness.  Before the public enquiry, inspectors should go to  Torness , just up from Berwick, and look at an unobtrusive building in a few acres of land and consider that this Torness reactor produces twenty five (yes, 25!) times as much as the proposed blot on the Kielder landscape.  In addition, as Centrica have pointed out, the cost of wind energy is £3 million per megawatt more than nuclear.  Wind energy is a means of taking money from the poor in the shape of high electricity prices and giving it to the rich, like Her Majesty the Queen or the Prime Minister’s father-in-law.  There were 20,000 deaths in Englandlast year for reasons connected to the cold.  The exact amount attributed to wind energy price increases has not been published.</p>
<p>The new Archbishop of Canterbury is concerned about the poor and is determined to stop Wonga, the pay day loan company.  Can we hope that he will put an end to the ridiculous subsidies that alone make it possible to put up a hundred Prescott’s follies at Kielder?</p>
<p>As far back as 2001, Professor James Lovelock FRS, whose brilliant experimental work enabled us to solve the problem of the hole in the ozone layer, pointed out that any intelligent person who was concerned about carbon dioxide emissions would press for the immediate construction of nuclear power stations.  This view was supported by the Royal Society (Britain’s top scientists), the heads of every engineering institution and Pope Benedict.  It is hoped that Archbishop Welby will join Pope Benedict XVI in stating that nuclear weapons are forbidden but civil nuclear power with appropriate safeguards can benefit mankind. </p>
<p>The recent Japanese earthquake killed about 20,000 people, many of them cremated by the fire following the destruction of the oil refinery.  On the other hand, the one nuclear reactor that was damaged caused no casualties and resulted in the well-known Guardian journalist George Monbiot agreeing with Professor Lovelock that any intelligent person concerned about carbon emissions should press for the immediate construction of nuclear reactors.</p>
<p>We are in serious danger of blackouts unless we go ahead quickly with fracking and the problems related to the fact that in 2003, Blair and Brown were only interested in their own electoratl prospects and failed to obtain cross-party agreement on building nuclear – instead we are landed with a forestof Prescott’s follies.</p>
<p>Let us hope that a little more intelligence is shown by our leaders at this stage and the beauty of Kielder be unmarked by Prescott’s follies.</p>
<p>Yours faithfully</p>
<p>T R MANLEY</p>
<?php include 'foot.php'; ?>